### PR TITLE
Initial translation

### PR DESCRIPTION
**Pull request by alesvaupotic**
File was a placeholder, copied from English.

### CODE REVIEW

**Comment by caouecs** [comment]
Hello @alesvaupotic,
thank you but you have a problem with StyleCi

After, can you help us with validation.php ?

**Comment by alesvaupotic** [comment]
Should be fine now, added a missing comma.

**Comment by alesvaupotic** [comment]
Validation.php seems partially translated. I can do the rest, sure.

**Comment by caouecs** [comment]
Thank you

**Pull request merged**
