### PR TITLE
Added IPv4 and IPv6 validation messages for all languages

### PR DESCRIPTION
**Pull request by billmn**

### CODE REVIEW

**Comment by dersvenhesse** [comment]
Wouldn't it be feasible to use the already translated strings for `ip` in every case and just replace `IP` with `IPv4` and `IPv6`?

**Comment by billmn** [comment]
@dersvenhesse Not in every case, for example take a look here: https://github.com/caouecs/Laravel-lang/blob/master/src/be/validation.php#L50

**Comment by dersvenhesse** [comment]
I assume `IPv6-адрасам` would work since it translates to `IPv6-address`. But I get your point, it might not be the most suitable way in all cases.

**Comment by caouecs** [comment]
Thank you

**Pull request merged**
