### PR TITLE
[de] Add german json for standard artisan make:auth

### PR DESCRIPTION
**Pull request by tpraxl**
After running `artisan make:auth`, there are still translations missing, because the published blade files use translation keys as strings (`__('E-Mail Address')`).

The required german translations are added with this commit.

### CODE REVIEW

**Comment by caouecs** [comment]
Hello @tpraxl,
sorry for the lag, but I don't find the English reference of your file.

You have defined this file from the code of the authentication page ?

Thanks

**Comment by pawelmysior** [comment]
Hi @caouecs, since Laravel 5.6.8 you can define translation strings in a JSON file.

There is no English version of the JSON file that @tpraxl proposed, because the `__()` helper will use the provided key (translation string) if no translation is found. You don't need the `en.json` file, because using `{{ __('E-Mail Address') }}` will just return `E-Mail Address`.

Read more in the documentation: https://laravel.com/docs/5.6/localization#using-translation-strings-as-keys

To me, this is a welcomed change. By the way, great job on creating and maintaining this package.

**Comment by caouecs** [comment]
Ok, but I need an english version of this file, just to generate a todo file

**Comment by caouecs** [comment]
And the file must be ordered by tag.

But I'm not sure to want json files directly in src directory.

**Comment by tpraxl** [comment]
Just updated the PR accordingly.

**Comment by caouecs** [comment]
Sorry, I didn't see your request when I asked for order ;)

=> I'm ok for json files. 

But... I think the English version should be in _script/en_ directory, and all json files in _src/{language}_ directory. It's just my point of view

**Comment by pawelmysior** [comment]
@caouecs I agree. Even though in a Laravel application the `de.json` should be placed directly in the `resources/lang` directory I think it would be cleaner for this repository to keep this file in the `src/de` directory.

**Comment by pawelmysior** [comment]
Also, since Laravel 5.6.25 the password reset notification uses the same mechanism, so we could also add those keys to the en.json and corresponding files:

```json
{
  "Reset Password Notification": "Reset Password Notification",
  "You are receiving this email because we received a password reset request for your account.": "You are receiving this email because we received a password reset request for your account.",
  "Reset Password": "Reset Password",
  "If you did not request a password reset, no further action is required.": "If you did not request a password reset, no further action is required."
}

**Comment by tpraxl** [comment]
@pawelmysior thanks for your suggestion. Please feel free to complement the files in your own PR after this PR has been merged.

**Comment by pawelmysior** [comment]
Will do 👍 no problem with the English file, the German might prove to be too difficult for me though 😄

**Comment by tpraxl** [comment]
@pawelmysior is "Reset Password Notification" the subject of the mail? If so, here's one possible german translation:

```
{
  "Reset Password Notification": "Passwort zurücksetzen",
  "You are receiving this email because we received a password reset request for your account.": "Sie erhalten diese E-Mail weil das Zurücksetzen des Passworts für Ihren Account angefordert wurde.",
  "If you did not request a password reset, no further action is required.": "Wenn Sie das Zurücksetzen Ihres Passworts nicht angefordert haben, können Sie diese E-Mail ignorieren."
}
```

This is one possible translation. Actually, it's not a 100% accurate translation. Translated back to English this would read:

```
{
  "Reset Password Notification": "Reset password",
  "You are receiving this email because we received a password reset request for your account.": "You are receiving this email because the reset of the password has been requested for your account",
  "If you did not request a password reset, no further action is required.": "If you did not request the reset of your password, you can ignore this email."
}
```

**Comment by pawelmysior** [comment]
Yes, have a look here:

https://github.com/laravel/framework/blob/f7ade7a7379ef144ebcb43a0ea59925571537377/src/Illuminate/Auth/Notifications/ResetPassword.php#L60-L63

**Comment by pawelmysior** [comment]
Hey @caouecs do you want help remaking the todo script to also check this new file?

**Comment by caouecs** [comment]
@tpraxl the English version in script/en directory, please

@pawelmysior with pleasure

**Comment by pawelmysior** [comment]
Ok, on it :)

**Comment by caouecs** [comment]
Danke

**Pull request merged**
