### PR TITLE
Ua

### PR DESCRIPTION
**Pull request by rela589n**
Simply ukrainian language files.

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
thanks you, but I don't see ua for ukrainian, I have uk.

Are there differences ?

**Comment by andrey-helldar** [comment]
It is interesting that Ukraine has a literal code of UA, not UK.

https://en.m.wikipedia.org/wiki/List_of_UIC_country_codes

**Comment by andrey-helldar** [comment]
@caouecs, I suggest replacing the use of the country code `uk` to `ua`.
I [did not find](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) information that `uk` refers to Ukraine.

> Although the country code top-level domain .gb is reserved for the United Kingdom, the UK uses the .uk country code top-level domain instead.

**Comment by caouecs** [comment]
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by andrey-helldar** [comment]
@rela589n, is there anything to counterbalance?

**Comment by andrey-helldar** [comment]
ISO 639-1 - contains alphabetic codes of languages. The letter code of the Ukrainian language is UK.

ISO 3166 - contains the alphabetic code of countries. The letter code of the country of Ukraine is UA.

**Comment by andrey-helldar** [comment]
ISO 639-1 - contains alphabetic codes of languages. The letter code of the Ukrainian language is UK.

ISO 3166 - contains the alphabetic code of countries. The letter code of the country of Ukraine is UA.

**Comment by andrey-helldar** [comment]
I suggest closing this PR, since the package uses language codes, not country codes.

**Pull request closed without merging**
