### PR TITLE
Update es\validation.php with custom attributes.

### PR DESCRIPTION
**Pull request by scrubmx**
Add spanish attributes the validation.php file.

### CODE REVIEW

**Comment by overtrue** [comment]
:-1:

**Comment by caouecs** [comment]
@scrubmx Gracias

@overtrue Why ?

**Comment by overtrue** [comment]
@caouecs https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php#L108

**Comment by scrubmx** [comment]
In spanish it is very common to have weird/wrong validation messages like:

* El campo de **body** es requerido

Instead the message should read:

* El campo de **contenido** es requerido

This patch just makes it more easy to customize said validation messages.

I also saw there was precedent for this kind of change in previous commits:
– https://github.com/caouecs/Laravel-lang/commit/d7fe0b7a6371d558cc784bbb7bce78b3d86c55bb
– https://github.com/caouecs/Laravel-lang/commit/0fb4fb3ab6d74ccd415ebcd34a26f7c2b11ea96c

**Comment by overtrue** [comment]
@scrubmx Well, I just thought it must be Consistent with the laravel/laravel, if previously done so, forgot my comment. :smile:

**Comment by arcanedev-maroc** [comment]
You can add `attributes` to your validation for a specific language without a problem.

Like this : https://github.com/caouecs/Laravel-lang/blob/master/fr/validation.php#L108-L138

The default validation `attributes` is empty because we use English as a fallback language (And we we write our code like attribute names, methods ... in English, DUH!).

So, :+1: for @scrubmx

**Pull request merged**
