### PR TITLE
[pl] Fix polish translations

### PR DESCRIPTION
**Pull request by pawelmysior**
Sorted the json file keys alphabetically, removed unused lines and added missing lines.

### CODE REVIEW

**Comment by caouecs** [comment]
Are you sure for unused lines ?

**Comment by pawelmysior** [comment]
Yes, have a look at my other PR: https://github.com/caouecs/Laravel-lang/pull/1033.

I checked all the strings that are used in a fresh Laravel 5.8 app.

**Comment by caouecs** [comment]
the master branch is not just for Laravel 5.8

**Comment by pawelmysior** [comment]
Oh, ok. Sorry about that. I'll fix this and the other PR.

**Comment by pawelmysior** [comment]
So what lines should be kept in the master branch and in the `todo.md` file? The ones needed in all Laravel versions from 5.1 till 5.7 or 5.8?

**Comment by ycs77** [comment]
You should push PR to laravel58 branch

**Pull request closed without merging**
