### PR TITLE
[ru] Laravel 5.7 and below checks the password length of six characters

### PR DESCRIPTION
**Pull request by andrey-helldar**
Information about the eight characters listed in the `laravel58` branch.

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
thank you, but just for laravel58 branch ;)

**Comment by andrey-helldar** [comment]
@caouecs, no, you did not understand me. In Laravel 5.7 the password is tested for a length of 6 (шесть) characters, and in the translation file it is written "восемь" (eight).

**Comment by andrey-helldar** [comment]
@caouecs, no, you did not understand me. In Laravel 5.7 the password is tested for a length of 6 (шесть) characters, and in the translation file it is written "восемь" (eight).
        22:39, 8 апреля 2019 г., Fred Delrieu <notifications@github.com>:Hello,
thank you, but just for laravel58 branch ;)

**Comment by andrey-helldar** [comment]
I fixed this error for versions 5.7 and lower.

**Comment by andrey-helldar** [comment]
0 - ноль (нуль)
1 - один
2 - два
3 - три
4 - четыре
5 - пять
6 - шесть
7 - семь
8 - восемь
9 - девять
10 - десять

**Comment by andrey-helldar** [comment]
`master` branch:

* [en] https://github.com/caouecs/Laravel-lang/blob/master/script/en/passwords.php#L15 - "Passwords must be at least six characters..."
* [ru] https://github.com/caouecs/Laravel-lang/blob/master/src/ru/passwords.php#L15 - "Пароль должен быть не менее восьми символов..." == "Passwords must be at least eight characters".


`laravel58` branch:

* [en] https://github.com/caouecs/Laravel-lang/blob/laravel58/script/en/passwords.php#L15 - "Passwords must be at least eight characters..."
* [ru] https://github.com/caouecs/Laravel-lang/blob/laravel58/src/ru/passwords.php#L15 - "Пароль должен быть не менее восьми символов..." == "Passwords must be at least eight characters".

**Comment by andrey-helldar** [comment]
@caouecs, did you see my messages?

**Comment by andrey-helldar** [comment]
@caouecs, did you see my messages?

**Comment by caouecs** [comment]
ok dokki, sorry ;)

**Comment by andrey-helldar** [comment]
np)

**Pull request merged**
