### PR TITLE
Improved todo.md page + refactored todo.php

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you

**Comment by caouecs** [comment]
I have a problem with the todo file, see https://github.com/caouecs/Laravel-lang/compare/problem_todo?expand=1 we don't have all languages

**Comment by caouecs** [comment]
I did "php script/todo.php"

**Comment by andrey-helldar** [comment]
Oh. I'll be at the computer soon and can check.

**Comment by andrey-helldar** [comment]
@caouecs, I apologize for the long reply.

Now I checked, my file is generated normally (73 languages).

Tell me, what version of php do you use to call the file?

I'm using 7.3.9.

See my changes to the `problem_todo` branch: https://github.com/caouecs/Laravel-lang/compare/problem_todo...andrey-helldar:patch-2019-11-25-15-57?expand=1

**Comment by caouecs** [comment]
I'm using PHP 7.3.10, I will review code this week-end

**Comment by andrey-helldar** [comment]
Write when you look.
If the problem persists, I will undo the structural changes to the previous view, retaining the new formatting style.
Just wanted to do the best 🙂

**Comment by andrey-helldar** [comment]
@caouecs, could you check?

**Comment by caouecs** [comment]
Done: I just add "sort" function

https://github.com/caouecs/Laravel-lang/commit/b508ae398fc1a8453a6877229e57460dd07ecfa2#diff-f195800201e43eae9603a08611e6f906

**Comment by andrey-helldar** [comment]
@caouecs, okay 😊

**Pull request merged**
