### PR TITLE
Translated comment section in auth.php

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**

### CODE REVIEW

**Comment by Maxim-Mazurok** [comment]
Hmm, what's wrong?

> The StyleCI analysis has failed

Maybe something messed up with lines length?

**Comment by caouecs** [comment]
the spaces at the end of lines ;)

**Comment by Maxim-Mazurok** [comment]
@caouecs oh, sorry.. fixed :)

**Comment by caouecs** [comment]
Thank you

**Pull request merged**
