### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by iggori**
added new langs

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
can you more explicit with your pull request ? list of languages for example ;)

**Comment by caouecs** [comment]
can you fix the problem with styleci ?

**Comment by caouecs** [comment]
@iggori ?

**Comment by iggori** [comment]
Sorry bro, I have no time, if you can please refactor and submit. This update is made by professional translators for our app. Its waste its not part of package. I'm sorry i can find time to do this on proper way. Tnx for understanding.

**Comment by caouecs** [comment]
Ok, no problem ;)

**Pull request merged**
