### PR TITLE
update BAHASA in password

### PR DESCRIPTION
**Pull request by idindrakusuma**
some of the use of language is less in accordance with KBBI (Kamus Besar Bahasa Indonesia) rules.

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
thank you

@idhamperdameian, is ok for you ?

**Comment by idhamperdameian** [comment]
@caouecs Yes it's look good for me.

**Comment by caouecs** [comment]
Thank you

**Comment by idindrakusuma** [comment]
Thank you @idhamperdameian :)
Y r welcome @caouecs 👍

**Comment by idhamperdameian** [comment]
Sama2 bro @idindrakusuma

**Pull request merged**
