### PR TITLE
Fixed format like original Laravel files

### PR DESCRIPTION
**Pull request by billmn**
Compared to original Laravel files, there are missing blank lines, an example here: https://github.com/laravel/laravel/blob/master/resources/lang/en/auth.php

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
it's critical ?

**Comment by billmn** [comment]
Hi, no it's not critical ... it's just a different format than the original files.
I think may be helpful to have them lined up, that's all ;)

**Comment by caouecs** [comment]
We need to update validation files too ;)

so, for the moment, I close this pull request

**Comment by billmn** [comment]
No problem ;)

**Pull request closed without merging**
