### PR TITLE
Using Сode Style to successfully pass the StyleCI test

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you

can you resolve conflicts ?

**Comment by andrey-helldar** [comment]
Done

**Comment by andrey-helldar** [comment]
You can configure the automatic application of changes based on your StyleCI settings:

2018-06-08 16-32-07 andrey-helldar api-response - styleci - google chrome

**Comment by caouecs** [comment]
Thank you

**Pull request merged**
