### PR TITLE
Add "Log In" and "Log Out"

### PR DESCRIPTION
**Pull request by jeff-h**
Fixes https://github.com/caouecs/Laravel-lang/issues/1262.

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you, but you don't add translations ?

**Comment by jeff-h** [comment]
Sorry, as is probably increasingly apparent, I have no clue what I'm doing lol. Should every json file have the new two entries added with English as a placeholder translation?

**Comment by caouecs** [comment]
If you add a new tag, you must translate at least in your language ;)

**Comment by jeff-h** [comment]
I only speak English 😳

**Comment by caouecs** [comment]
The aim of this project is not to translate sites ;)

**Comment by jeff-h** [comment]
I am happy to make changes to my PR but I'm not sure what's needed, sorry.

**Comment by caouecs** [comment]
I think I will close this PR, because it's not directly for the Laravel framework.

But, why not create a new repository with some basic words, expressions... in json files which can be translated by the community ?

**Pull request closed without merging**
