### PR TITLE
Fix indent

### PR DESCRIPTION
**Pull request by juukie**
Now equal to the [original file](https://raw.githubusercontent.com/laravel/laravel/master/resources/lang/en/validation.php).

### CODE REVIEW

**Comment by caouecs** [comment]
We don't respect the original file, we have our own phpcs ;)

**Comment by juukie** [comment]
But the [en file](https://github.com/caouecs/Laravel-lang/blob/master/en/validation.php) stays original?

**Comment by caouecs** [comment]
it's my fault

**Comment by juukie** [comment]
Ok. I see you've updated it.

**Pull request closed without merging**
