### PR TITLE
[UZ] new language

### PR DESCRIPTION
**Pull request by zvermafia**
Added Uzbek language with latin and cyrillic versions.

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you, but delete the commit 53ff47b

**Comment by zvermafia** [comment]
@caouecs I did as you wrote

**Comment by caouecs** [comment]
same problem, 73 updated files

can you do a new pull request with just files for Uzbek language ?

**Comment by zvermafia** [comment]
I'm sorry but I just follow contributing guide. And there written:

> run PHP-cs-fixer
if installed to project local, run vendor/bin/php-cs-fixer fix

I just ran `vendor/bin/php-cs-fixer fix` and it touched other files :(. What, is it wrong guide or I did something wrong?

**Comment by caouecs** [comment]
Ok, we used a old version of php_cs, I updated it

**Comment by zvermafia** [comment]
Could you help me, I don't understand what's wrong...

My steps after you updated php_cs:

1. I destroyed my commit with the fixing code styles (where I ran `vendor/bin/php-cs-fixer fix`);
2. And I just left only one commit with adding a new language;
3. Made rebase (`git pull --rebase upstream master`);
4. `composer update` (but it's changed nothing);
5. Ran `vendor/bin/php-cs-fixer fix`;
6. Squashed my commits into one commit;
7. Pushed with `git push origin uz-lang --force`.

Where made I mistake?

**Comment by caouecs** [comment]
Your code is ok, but the project has a configuration problem with StyleCI, I will fix it

**Comment by caouecs** [comment]
Thank you

**Comment by zvermafia** [comment]
Thanks, I'm happy!

**Pull request merged**
