### PR TITLE
Fixed 'da' language

### PR DESCRIPTION
**Pull request by wogelius**

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
capital letter for variables ? you are sure ?

**Comment by wogelius** [comment]
Hi,

yes, but only if the variable is the first word in a sentence, like here (validation.php):
    'image'                => ':Attribute skal være et billede.',

I have not replaced the varibles inside a sentence like this:
    'in'                   => 'Det valgte :attribute er ugyldig.',

The functionality for capitalization is described here:
https://laravel.com/docs/5.2/localization#basic-usage

**Comment by caouecs** [comment]
Oki, but it's just for Laravel 5.2... I think it will be included in v3 of this project.

For the moment, I prefer no capital letter ; the v3 comes to the end of the month

**Comment by wogelius** [comment]
Ok, i see.
I didn't realize the version you are targeting.
I will just keep my own branch for the moment, and maybe make a pull request when your v3 is ready :)

**Comment by caouecs** [comment]
Hello @wogelius,
can you do a pull request just with updates without :Attribute ? ;)

Thanks

**Comment by wogelius** [comment]
Hi @caouecs 
Sure, i have committed a new version :)

Best regards
Thomas

**Comment by caouecs** [comment]
Thanks

**Pull request merged**
