### PR TITLE
Update validation.php

### PR DESCRIPTION
**Pull request by whsyu**
minor translation update for traditional chinese

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
thanks but for chinese version, I call @overtrue ;)

**Comment by whsyu** [comment]
no problem, waiting for his review ;)

**Comment by overtrue** [comment]
Hi, @caouecs,  I was in mainland China, @whsyu is Taiwanese, so zh-TW his work should be more accurate. Thank you!  so, just merge it. :smile: 

谢谢！@whsyu

**Comment by caouecs** [comment]
Ok ;)

**Pull request merged**
