### PR TITLE
Update passwords.php

### PR DESCRIPTION
**Pull request by marijnz0r**
Change translation to be grammatically correct

### CODE REVIEW

**Comment by robindirksen1** [comment]
@marijnz0r why is this one word? www.vandale.nl don't recognise this as one word. Also Google Translate suggest it to be splitted in 3 words.

**Comment by marijnz0r** [comment]
I'm using this in my application. It's supposed to be written as one word. https://onzetaal.nl/taaladvies/samenstelling

On Mar 15, 2018 13:35, Robin Dirksen <notifications@github.com> wrote:

@marijnz0r<https://github.com/marijnz0r> why is this one word? www.vandale.nl<http://www.vandale.nl> don't recognise this as one word. Also Google Translate suggest it to be splitted in 3 words.

**Comment by robindirksen1** [comment]
Okay, I agree. If you search it on Google you also find 1 other post which uses this word: https://www.google.nl/search?source=hp&ei=5neqWueXGIWZsAe5zrOgAg&q=%22wachtwoordhersteltoken%22&oq=%22%22&gs_l=psy-ab.3.0.35i39k1l10.584.1585.0.2304.7.6.0.0.0.0.225.495.1j1j1.4.0....0...1c.1.64.psy-ab..3.4.742.6..0j0i131k1.249.MjAQfuJgS4o

**Comment by marijnz0r** [comment]
Cool! I can't seem to fix the StyleCi, though. Could you help me to fix it?

**Comment by caouecs** [comment]
Thank you

**Pull request merged**
