### PR TITLE
[nl] Make sentences start with a capital letter

### PR DESCRIPTION
**Pull request by pdutourgeerling**
When using `:attribute` sentences start with a lowercase letter. Using `:Attribute` makes the sentences start with a capital letter.

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
thank you, but if we change here, we must change for every languages ;)

**Comment by pdutourgeerling** [comment]
I understand. I see someone else already did the same in #627. Do you already have plans to change the sentences?
Looking at Laravel's code, using `:Attribute` will break the language for all versions prior to 5.2.

**Comment by caouecs** [comment]
We can do a v4 of this package for Laravel 5.2+ with :Attribute

**Comment by pdutourgeerling** [comment]
Sounds like a good idea.
While it is possible to replace all sentences starting with `:attribute` to start with `:Attribute`, there are probably some exceptions in some languages.
Another option would be to let the community translate it.

I don't like to say it but I'm currently too busy to work on it. I leave this PR open but if you want to close it I am OK.

**Comment by caouecs** [comment]
Hello,
I added a new branch for letters capitalized.

You can add your work, now ;)

**Comment by pdutourgeerling** [comment]
@caouecs Updated the branch 👍

**Comment by caouecs** [comment]
Hello,
can you add validation.ipv4 and validation.ipv6 ?

Thank you

**Comment by pdutourgeerling** [comment]
See PR #699

**Pull request closed without merging**
