### PR TITLE
Add Georgian translation line

### PR DESCRIPTION
**Pull request by ottoshmidt**
One of the lines in validation.php wasn't translated before.

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
thanks. Can you translate "in_array" too ?

**Comment by ottoshmidt** [comment]
I'll try. Do you want me to put it into a separate commit or squash into this one?

**Comment by caouecs** [comment]
same commit ;)

**Comment by caouecs** [comment]
For georgian, we need :

* distinct
* present

**Comment by ottoshmidt** [comment]
sorry had been busy so far.

**Comment by caouecs** [comment]
No problem ;)

**Pull request merged**
